### ISSUE TITLE
Cannot redeclare _() in wordpress-stubs.php on line 94569

### ISSUE THREAD

**Issue by jdeniau** [GiacoCorsiglia/wordpress-stubs#3]
By just downloading the stub file and executing `php -l wordpress-stubs.php`, I got this error :

```
PHP Fatal error:  Cannot redeclare _() in wordpress-stubs.php on line 94569
```

I did not found another declaration of the `_` function, but maybe you have an idea ?

**Comment by szepeviktor** [comment]
Fixed.

**Comment by localheinz** [comment]
@jdeniau 

The issue isn't actually fixed yet, since #4 has not been merged yet.

**Comment by GiacoCorsiglia** [comment]
The cause for this issue is that I did not have the `gettext` PHP extension installed when generating the stubs.  [This line](https://github.com/GiacoCorsiglia/php-stubs-generator/blob/master/src/NodeVisitor.php#L315) in GiacoCorsiglia/php-stubs-generator in general prevents against this scenario, but of course won't exclude functions from inactive extensions.

Explicitly excluding `wp-includes/compat.php` as in #4 is probably the way to go, but just FYI @localheinz .

**Comment by localheinz** [comment]
Should be fixed, please update your stubs by running

```
$ composer require giacocorsiglia/wordpress-stubs:4.9.8.1
```

Feel free to reopen when you are still having issues.
